### ISSUE TITLE
Context is not working

### ISSUE THREAD

**Issue by Bartzy** [jenssegers/laravel-raven#10]
Hi,

The Context examples do not work for me (hosted version of Sentry), on Laravel 4.1.
https://github.com/jenssegers/laravel-raven#context-informaton

Am I doing anything wrong?

**Comment by Bartzy** [comment]
OK, actually sending tags is working, but this example ignores the extra data:
```
Log::error('Something went wrong', [
   'download_size' => 3432425235
]);
```

**Comment by jenssegers** [comment]
Shouldn't these be passes using the `extra` index? Or did the raven client change recently?

**Comment by jenssegers** [comment]
But then again, it would be easier if anything that is not user or tags will be send as extra.

**Comment by jenssegers** [comment]
Fixed in https://github.com/jenssegers/laravel-raven/commit/6b22591f68718069fb46516ee4e44fc0d86753a7

**Comment by Bartzy** [comment]
Great, thanks!

Are you going to tag a release soon?
