### ISSUE TITLE
Fatal error :scream: when I run php artisan migrate in console

### ISSUE THREAD

**Issue by yoelfme** [jenssegers/laravel-raven#11]
PHP Fatal error:  Uncaught exception 'ErrorException' with message 'Use of undefined constant CURLOPT_VERBOSE - assumed 'CURLOPT_VERBOSE'' in /data/www/vendor/raven/raven/lib/Raven/Client.php:596

**Comment by jenssegers** [comment]
Looks like an issue with the original raven library. https://github.com/getsentry/raven-php

**Comment by jenssegers** [comment]
Double check if you have CURL installed btw.
