### ISSUE TITLE
Composer Update Fails with Php v5.5.9

### ISSUE THREAD

**Issue by shpendk** [jenssegers/laravel-raven#12]
Hi

I have the following php version:
PHP 5.5.9-1ubuntu4.9 (cli) (built: Apr 17 2015 11:44:57)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies

When i do composer update, i receive the following error:
Call to undefined function Jenssegers\Raven\env() in /var/www/vendor/jenssegers/raven/src/RavenServiceProvider.php on line 40

I have tracked it down to the problem that the function "env()" does not exist in PHP 5.5.9 but does in older versions (i.e. 5.4)

Any possible fix for this?

**Comment by jenssegers** [comment]
You are probably using Laravel 4?

**Comment by shpendk** [comment]
Yeah

**Comment by jenssegers** [comment]
Fixed on dev-master

**Comment by jenssegers** [comment]
Tagged `v1.4.4`
