### ISSUE TITLE
"Class log does not exist" error 

### ISSUE THREAD

**Issue by shpendk** [jenssegers/laravel-raven#13]
Hi Man

After the fix with getenv, now i'm getting the following error:
"Class log does not exist" in /­vendor/­jenssegers/­raven/­src/­RavenServiceProvider.php:64

problematic code:
```
 $this->app['log']->listen(function ($level, $message, $context) use ($app)
```

**Comment by jenssegers** [comment]
Fixing it as we speak.

**Comment by shpendk** [comment]
Awesome man, thank you for quick response(s) :)

**Comment by jenssegers** [comment]
That should fix it. Let me know if it's still failing.
