### ISSUE TITLE
Still sending errors with level "none"

### ISSUE THREAD

**Issue by Bartzy** [jenssegers/laravel-raven#14]
Hi,

I have set the "level" parameter in the config to "none" in the testing environment.
However, errors are still being sent when I run unit tests (and there are errors...)

Should I disable Raven/Sentry in some other way?

Thanks.

**Comment by Bartzy** [comment]
@jenssegers Did you perhaps had the time to look at this issue?

Thanks!

**Comment by mfn** [comment]
I'm not sure, but it seems to me a bug in the logic?
```PHP
        // Check if we want to log this message.
        if ($this->parseLevel($level) < $this->level)
        {
            return;
        }

```
This is straight from https://github.com/jenssegers/laravel-raven/blob/21fb075b113ad0bb61e89fb76fee9b63684f3cff/src/RavenLogHandler.php#L53-L56 .

Now assume:
- `$this->level` is by default `debug`, which is number `100`
- now `$level === 'error'` which means `$this->parseLevel($level)` will return 400
- thus the logic check will be `if (400 < 100)` which can't work

This, right now, the only way to actually get ALL messages is to set it to `none` in the first place.

@Bartzy another way to simply have it disabled is by putting the `RAVEN_DSN` in your `.env`; but only in production.

**Comment by jenssegers** [comment]
Added some more tests and it seems to not send anything for me.
