### ISSUE TITLE
Installstion throws exception

### ISSUE THREAD

**Issue by rsands2801** [jenssegers/laravel-raven#17]
In laravel 5.1 I am getting InvalidArgumentException Raven DSN Not configured despite the .env file and the services.raven.dsn config being present.

The script is working on another system that was installed and then raven added to it but with a fresh install this exception wont let it install

**Comment by rsands2801** [comment]
@jenssegers Any luck with this or are we doing something wrong?

**Comment by jenssegers** [comment]
Can you try the master branch? Did some small tweaks.

**Comment by rsands2801** [comment]
@jenssegers Thanks, from what I can see it looks like it will work - we will be deploying a new site in the next few weeks and will be able to test
