### ISSUE TITLE
Use of env() breaks Laravel 4 support

### ISSUE THREAD

**Issue by wlcx** [jenssegers/laravel-raven#18]
2203184 seemingly broke Laravel 4 support with [this](https://github.com/jenssegers/laravel-raven/commit/2203184061d5f571437f3a836a8f3d20933e7fd5#diff-bfa7170626d0c73edadc3a514e71aa26R62) line, as env() is not a helper function in laravel 4.

**Comment by jenssegers** [comment]
Ah damn it, will have to failback to getenv I guess.

**Comment by jenssegers** [comment]
Fixed on master.
