### ISSUE TITLE
Laravel 4.2 - Contextbuilder

### ISSUE THREAD

**Issue by Alexwijn** [jenssegers/laravel-raven#20]
After updating to v1.7.0 the package stopped working in Laravel v4.2. It is unable to find the Illuminate\Contracts\Container\Container class. After some research I found out that this class is only available in Laravel 5 and not in 4.2.

Edit: seems like this got broken since v1.6.0

**Comment by atayahmet** [comment]
Not working high version than v1.2.* in Laravel v4.2. It's need to downgrade to 1.2.* for L4.2

**Comment by Alexwijn** [comment]
Working fine here at here at v1.5.1. Make sure you use the `Raven_Client` context and not the old `raven`.

**Comment by jenssegers** [comment]
Can you try v1.7.1?

**Comment by Alexwijn** [comment]
Sure thing, I'll let you know within 24 hours.

**Comment by Alexwijn** [comment]
I'm sorry for a late reply but the latest version do seem to fix the problem.
