### ISSUE TITLE
Feature request: adding an on/off option about registerShutdownFunction

### ISSUE THREAD

**Issue by ifduyue** [jenssegers/laravel-raven#21]
Hello,

There is a none level to not to send messages to sentry, but no way to not to registerShutdownFunction.

**Comment by ifduyue** [comment]
@jenssegers What's your thought?

**Comment by ivokund** [comment]
Just came across this as well. This in should be executed only if the $level is not "none" ( `\Jenssegers\Raven\RavenServiceProvider::register`)

```php
// Register the fatal error handler.
register_shutdown_function(function () {
	if (isset($this->app['Raven_Client'])) {
		(new Raven_ErrorHandler($this->app['Raven_Client']))->registerShutdownFunction();
	}
});
```

Otherwise fatal errors will still be logged to Sentry.

**Comment by ifduyue** [comment]
Revan_errorHandler->registerShutdownFunction basically calls register_shutdown_function, which is also done by laravel in [src/Illuminate/Foundation/Bootstrap/HandleExceptions.php](https://github.com/laravel/framework/blob/5.1/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php#L37).
No matter laravel-raven register shutdown function or not, exception will always be handled.

**Comment by ivokund** [comment]
I don't mind fatal errors being handled by Laravel, but if there's a setting for disabling Sentry error reporting then I really don't want anything from that environment to reach Sentry.

**Comment by ifduyue** [comment]
> I don't mind fatal errors being handled by Laravel, but if there's a setting for disabling Sentry error reporting then I really don't want anything from that environment to reach Sentry.

That's why you should let laravel handle exceptions. According to https://laravel.com/docs/5.1/errors#the-exception-handler, you can filter what errors/exceptions go to sentry. And there is no need to do environment check if logging level is none https://github.com/laravel/framework/blob/5.1/src/Illuminate/Foundation/Exceptions/Handler.php#L49-L51

**Comment by jenssegers** [comment]
They best way of disabling Sentry for an environment would be to conditionally load the service provider as mentioned in the readme here: https://github.com/jenssegers/laravel-raven#installation

**Comment by ifduyue** [comment]
> They best way of disabling Sentry for an environment would be to conditionally load the service provider as mentioned in the readme here: https://github.com/jenssegers/laravel-raven#installation

This is not the best way. Raven facade needs to be taken care of, too.
