### ISSUE TITLE
Disable sending events when debug = true or Envoiroment = local,dev

### ISSUE THREAD

**Issue by rubberneck** [jenssegers/laravel-raven#4]
It would be nice if there was a way to disable this when developing. Is there some way to setup the configuration so this would be possible? Right now i am just doing

```
if (!Config::get('app.debug')) {
    // Register listeners
    $this->registerListeners();
}
```

I still need everything to register so that my code still works, I just need to disable sending the events or the log listeners. 

For example i need this code to work all the time but when i am developing i would like it not to send the event to the sentry server.

```
App::error(function(Exception $exception, $code)
{
    if (Auth::user()) {
        Raven::user_context(Auth::user()->toArray());
    }
    Log::error($exception);

});
```

**Comment by Bartzy** [comment]
@jenssegers 
Sorry for bumping this issue - What level should I use in the config to disable logging completely (in the dev environment)?

How do you approach logging in the dev environment? You disable Raven completely?

Thanks!

**Comment by jenssegers** [comment]
One solution would be to use `env('LOG_LEVEL', 'info')` in your configuration file. So that you can specify `LOG_LEVEL=none` or `LOG_LEVEL=warning` as environment variable or in your .env file.

**Comment by Bartzy** [comment]
Is that Laravel 5? I'm using Laravel 4.0 ATM.
I didn't quite understand what did you mean.

**Comment by jenssegers** [comment]
Yes, the .env files are Laravel 5.

**Comment by Bartzy** [comment]
So setting level => 'none' in the services.php config - that would disable logging entirely?

**Comment by jenssegers** [comment]
Yes

**Comment by Bartzy** [comment]
Great, thanks!

Out of curiosity, do you usually disable logging to Sentry on development environments?

**Comment by jenssegers** [comment]
Depends on the project. Sometimes in enable it, sometimes I create a separate sentry DSN for both production and dev, and sometimes I just disable it.
