### ISSUE TITLE
Shutdown Function and error handler not set. 

### ISSUE THREAD

**Issue by sysadmind** [jenssegers/laravel-raven#8]
Accoring to the official php raven client docs at https://github.com/getsentry/raven-php/blob/master/README.rst, the raven client has the ability to register itself for shutdown functions and error/exception handling. Is there a reason that this process doesn't happen in laravel-raven? It seems that if the code had a fatal error, that's something you would want to submit a bug to sentry for. It would seem that when the client is instantiated, the raven client could call its functions to register the client for these operations. I don't think it would change any of the laravel functionality.

**Comment by Bartzy** [comment]
Hi,

I'm also interested in this since it can be very handy to get fatal errors to Sentry as well.

**Comment by jenssegers** [comment]
Fixed :)

**Comment by sysadmind** [comment]
Thanks a million! Great project!

**Comment by jenssegers** [comment]
Will tag a new version once Travis is done.

**Comment by jenssegers** [comment]
New version is v1.4.0.

**Comment by Bartzy** [comment]
FYI - I added an ```App::fatal``` listener and logged PHP fatal errors there using Log::critical. It works nicely.
I think that Laravel registers an error handler, turns these errors to exceptions, and also triggers callbacks that your registered through ```App::fatal```.

**Comment by jenssegers** [comment]
For Laravel 4? I don't see a fatal method for Laravel 5.

**Comment by Bartzy** [comment]
Oh yeah, sorry for not mentioning that. I was talking about Laravel 4.

I didn't dig into Laravel 5's way of doing error handling, but I see it does register a shutdown function: https://github.com/laravel/framework/blob/89fcc958286c4105fbe24bf103f6c4d1fc2d6a5e/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php#L33

So perhaps there's an API for registering a callback through Laravel and not directly?

**Comment by jenssegers** [comment]
From what I am seeing, Laravel 5 should trigger the `report` method for fatal exceptions as well, so it should not even be necessary to register the shutdown handler. But I can't say for sure though.
